import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import FooterMenu from "./component/footerMenu";
import UserInfoWrite from "./component/userInfoWrite";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </head>
      <body style={{height: "100%"}} className="bg-[#f7f7f7]">
        {children}
        <FooterMenu />
      </body>
    </html>
  );
}