import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import FooterMenu from "./component/footerMenu";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        {/* <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"></link> */}
        <link rel="stylesheet" href="effectjs/effect-js.min.css" />
      </head>
      <body style={{height: "100%"}} className="bg-slate-50">
        {children}
        <FooterMenu />
        <Script src="effectjs/effect-js.min.js" strategy="afterInteractive" />
      </body>
    </html>
  );
}